export const FETCH_LIST_ITEMS = "LIST/FETCH_LIST_ITEMS";
export const REQUEST_LIST_ITEMS = "LIST/REQUEST_LIST_ITEMS";
export const NO_MORE_ITEMS = "LIST/NO_MORE_ITEMS";
export const FETCH_CHARACTER_INFO = "CHATACTER/FETCH_CHARACTER_INFO";
export const REQUEST_CHARACTER_INFO = "CHATACTER/REQUEST_CHARACTER_INFO";
